"""empty message

Revision ID: 46641a4db759
Revises: 
Create Date: 2024-03-27 12:46:52.659607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46641a4db759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mushrooms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)

    with op.batch_alter_table('user_mushrooms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('jenis_jamur',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mushrooms', schema=None) as batch_op:
        batch_op.alter_column('jenis_jamur',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('mushrooms', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
