"""empty message

Revision ID: 5c75660f1c33
Revises: 46641a4db759
Create Date: 2024-03-27 17:32:27.668719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c75660f1c33'
down_revision = '46641a4db759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edibles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('mineral', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('vitamin', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('penggunaan_kuliner', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manfaat_kesehatan', sa.Text(), nullable=True))
        batch_op.alter_column('kalori',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('lemak',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('kalium',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('karbohidrat',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.drop_column('natrium')

    with op.batch_alter_table('inedibles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toksisitas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gejala', sa.Text(), nullable=True))
        batch_op.drop_column('poison_name')
        batch_op.drop_column('amount')

    with op.batch_alter_table('mushrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deskripsi', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mushrooms', schema=None) as batch_op:
        batch_op.drop_column('deskripsi')

    with op.batch_alter_table('inedibles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', mysql.DOUBLE(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('poison_name', mysql.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('gejala')
        batch_op.drop_column('toksisitas')

    with op.batch_alter_table('edibles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('natrium', mysql.DOUBLE(asdecimal=True), nullable=True))
        batch_op.alter_column('karbohidrat',
               existing_type=sa.String(length=250),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('kalium',
               existing_type=sa.String(length=250),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('lemak',
               existing_type=sa.String(length=250),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('kalori',
               existing_type=sa.String(length=250),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.drop_column('manfaat_kesehatan')
        batch_op.drop_column('penggunaan_kuliner')
        batch_op.drop_column('vitamin')
        batch_op.drop_column('mineral')
        batch_op.drop_column('protein')

    # ### end Alembic commands ###
